"""
ABSTRACT
--------
User manual shown from the AutoMapper Help button.

The Help window is intentionally written as an operating manual for the GUI.
It explains setup, measurement, file handling, Results analysis, exporting, and
common failure behavior without duplicating the CompleteEASE instrument manual.
"""

from PyQt6.QtWidgets import QDialog, QLabel, QScrollArea, QVBoxLayout, QWidget


class HelpDialog(QDialog):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Ellipsometer AutoMapper — User Guide")
        self.resize(780, 760)

        root = QVBoxLayout(self)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)

        content = QWidget()
        layout = QVBoxLayout(content)

        text = QLabel(
            "<h1>Ellipsometer AutoMapper</h1>"
            "<p>AutoMapper performs predefined XY mapping measurements and "
            "provides a separate workspace for mapping analysis. The program "
            "is organized into two main tabs: <b>Measurement</b> and "
            "<b>Results</b>.</p>"

            "<h2>1. Computer Configuration</h2>"
            "<p>Computer-specific paths are stored in <b>config.json</b>. "
            "Two locations are required:</p>"
            "<ul>"
            "<li><b>staging_folder</b>: temporary folder where the selected "
            "CompleteEASE recipe saves its .SE and .txt files.</li>"
            "<li><b>default_experiment_parent</b>: default parent directory "
            "where AutoMapper creates permanent experiment folders.</li>"
            "</ul>"
            "<p>Paths may be absolute or relative. Relative paths are resolved "
            "from the AutoMapper program folder.</p>"

            "<h2>2. CompleteEASE Recipes</h2>"
            "<p>Recipes used with the real instrument must be available in the "
            "standard/common recipe location recognized by CompleteEASE so "
            "that they are returned by <b>ListRecipes()</b>. Configure the "
            "recipe itself to save its measurement output into the same folder "
            "listed as <b>staging_folder</b> in config.json.</p>"
            "<p>AutoMapper supplies the point filename to the recipe; the recipe "
            "controls the actual measurement, model, alignment steps, and save "
            "location. Refer to the CompleteEASE manual for recipe creation, "
            "alignment, optical models, fitting, and other instrument-specific "
            "settings.</p>"

            "<h2>3. Measurement Source</h2>"
            "<p>At the top of Measurement Setup choose the measurement source:</p>"
            "<ul>"
            "<li><b>SIMULATOR</b>: software-only development mode. It simulates "
            "CompleteEASE, the recipe, and the ellipsometer and writes test "
            "files into the configured staging folder.</li>"
            "<li><b>CompleteEASE</b>: connects to the real CompleteEASE remote "
            "interface on the local computer.</li>"
            "</ul>"
            "<p>Select <b>Connect</b>. After a successful connection, the Recipe "
            "drop-down is populated by that source. The simulator and real "
            "CompleteEASE use the same AutoMapper workflow.</p>"

            "<h2>4. Measurement Setup</h2>"
            "<p><b>Recipe:</b> choose the recipe to run at every measured point.</p>"
            "<p><b>Map name:</b> optional descriptive name. AutoMapper always "
            "adds a timestamp, so the experiment folder remains unique.</p>"
            "<p><b>Save location:</b> parent directory for the experiment. Each "
            "new run creates a new timestamped subfolder; measurements from "
            "different experiments are never intentionally combined.</p>"
            "<p><b>Grid:</b> choose the square map size. <b>Spacing</b> is the "
            "center-to-center distance between mapping positions in millimeters. "
            "Mapping span and total point count are shown automatically.</p>"

            "<h3>Experiment Folder</h3>"
            "<p>A run is stored approximately as:</p>"
            "<p><b>YYYYMMDD_HHMMSS_OptionalName/</b><br>"
            "&nbsp;&nbsp;raw_data/ &nbsp;(.SE and .txt point files)<br>"
            "&nbsp;&nbsp;results/ &nbsp;(recommended location for user exports)<br>"
            "&nbsp;&nbsp;mapping_results.csv</p>"
            "<p>Raw point filenames use their map coordinates, for example "
            "<b>X-4_Y2.txt</b> and <b>X-4_Y2.SE</b>.</p>"

            "<h2>5. Automatic XY Stage</h2>"
            "<p>Select <b>Low-Profile Automatic XY Stage</b>. The stage section "
            "appears below Measurement Setup.</p>"
            "<ol>"
            "<li>Select <b>SIMULATOR</b> for software testing or select the real "
            "COM port and press <b>Connect</b>.</li>"
            "<li>Use the arrow controls and jog step to place the ellipsometer "
            "beam over the desired center of the mapping area.</li>"
            "<li>Select <b>Set Mapping Center</b>. This defines the current stage "
            "position as map coordinate (0, 0).</li>"
            "</ol>"
            "<p>The mapping sequence then moves automatically through the grid.</p>"

            "<h2>6. Manual Stage</h2>"
            "<p>Select <b>Manual Stage</b> when the user will position the sample "
            "by hand. Before every point, AutoMapper displays the requested map "
            "coordinate.</p>"
            "<p>The prompt is designed for keyboard operation:</p>"
            "<ul>"
            "<li><b>Left / Right arrows</b>: change the highlighted action.</li>"
            "<li><b>Enter</b>: activate the highlighted action.</li>"
            "<li><b>Measure</b>: run the selected CompleteEASE recipe.</li>"
            "<li><b>Skip Point</b>: do not request a measurement; the point is "
            "marked as missing and mapping continues.</li>"
            "<li><b>Abort</b>: stop requesting additional mapping points.</li>"
            "</ul>"
            "<p><b>Track absolute coordinates</b> is optional. Enter the X/Y "
            "reading of the manual stage at the map center. The prompt then "
            "shows both the relative map coordinate and the absolute stage "
            "position. Absolute coordinates are only an operator aid; filenames "
            "and Results always use the relative map coordinates.</p>"

            "<h2>7. Before Starting a Real Mapping Run</h2>"
            "<ol>"
            "<li>Place the sample at the intended center and verify that the "
            "ellipsometer can acquire useful data there.</li>"
            "<li>Run the intended recipe manually in CompleteEASE at least once.</li>"
            "<li>Confirm that the optical model and fitted parameters are "
            "appropriate for the sample.</li>"
            "<li>Confirm that the recipe writes its .SE/.txt output to the "
            "configured staging folder.</li>"
            "<li>If the recipe performs alignment at every point, it can handle "
            "local alignment during the map. If alignment is intentionally "
            "omitted, prepare the recipe/sample according to the CompleteEASE "
            "procedure before starting AutoMapper.</li>"
            "</ol>"

            "<h2>8. Measurement Quality</h2>"
            "<p><b>Measurement Quality…</b> can flag measurements whose MSE "
            "exceeds a user-defined threshold. A high-MSE point is shown in "
            "orange in the Measurement progress map. This is a warning only; "
            "the measurement remains valid and is not automatically excluded "
            "from Results.</p>"

            "<h2>9. Starting, Aborting, Failures, and Retakes</h2>"
            "<p>Select <b>Start Measurement</b> after the measurement source is "
            "connected and the setup is valid.</p>"
            "<p><b>Abort</b> stops the AutoMapper sequence. It does not attempt "
            "to cancel a CompleteEASE recipe already in progress; the current "
            "request is allowed to finish and no next point is requested.</p>"
            "<p>A point is accepted when the expected TXT result is newly "
            "produced and can be parsed. If no usable TXT result is produced, "
            "the point is shown as a red failed/missing point and mapping "
            "continues. A failed point has no Results-table row.</p>"
            "<p>A CompleteEASE communication failure is different: AutoMapper "
            "stops the mapping sequence and displays an error message.</p>"
            "<p>Select a measured or failed point in the progress map (or a "
            "measured row in the table) and use <b>Retake Selected Point</b>. A "
            "successful retake replaces/creates the valid point. If retaking a "
            "previously valid point fails, the previous valid permanent result "
            "is kept.</p>"

            "<h2>10. Measurement Progress</h2>"
            "<p>The progress map uses the planned map coordinates:</p>"
            "<ul>"
            "<li>Gray: pending</li>"
            "<li>Yellow: current</li>"
            "<li>Green: measured</li>"
            "<li>Orange: measured but above the selected MSE warning threshold</li>"
            "<li>Red X: missing/failed/skipped</li>"
            "</ul>"
            "<p>Map-point and table-row selection are linked. Clicking the "
            "currently selected item again clears the selection.</p>"

            "<h2>11. Results Data Sources</h2>"
            "<p>Results updates live from the current measurement. It can also "
            "be used independently:</p>"
            "<ul>"
            "<li><b>Import TXT Folder</b>: parse coordinate-named CompleteEASE "
            "TXT result files.</li>"
            "<li><b>Import Table</b>: load an existing CSV table containing X "
            "and Y coordinates plus numeric parameters.</li>"
            "</ul>"
            "<p>The parser also accepts the older coordinate filename form "
            "<b>(-1,0).txt</b>. Imported datasets may contain irregular XY "
            "positions; plot types requiring a regular grid may then be "
            "unavailable.</p>"

            "<h2>12. Results Selection and Ignoring Points</h2>"
            "<p>Click an actual measured point or its table row to select it. "
            "Use <b>Ignore Point</b> to remove that measurement from interpolation "
            "and statistics. An ignored valid point appears as a red X during "
            "analysis and may be re-enabled. Missing/failed points do not exist "
            "as Results rows and therefore cannot be enabled.</p>"
            "<p>Ignored, missing, and temporary selected-point markers are not "
            "shown as data in exported scientific plots.</p>"

            "<h2>13. Plot Types</h2>"
            "<ul>"
            "<li><b>Interpolated Map</b>: continuous interpolated color map.</li>"
            "<li><b>Contour Map</b>: interpolated map with contour lines.</li>"
            "<li><b>Measured Points + Values</b>: actual measured coordinates "
            "with numerical labels.</li>"
            "<li><b>Pixel / Cell Map</b>: regular-grid cells without continuous "
            "interpolation; available only when the coordinates form a regular grid.</li>"
            "<li><b>3D Surface</b>: three-dimensional visualization of the "
            "interpolated surface.</li>"
            "<li><b>Histogram</b>: distribution of the selected parameter over "
            "included measured points.</li>"
            "</ul>"

            "<h2>14. Plot Options and Export</h2>"
            "<p><b>Plot Options…</b> is the primary location for plot formatting "
            "and export. It includes:</p>"
            "<ul>"
            "<li>Plot title and colorbar title.</li>"
            "<li>X/Y axis ranges: Auto or user-defined.</li>"
            "<li>X/Y tick spacing: Auto or user-defined.</li>"
            "<li><b>Reset Plot Settings</b>.</li>"
            "<li><b>Include measured-point markers</b> for exported plots. "
            "Markers remain visible in the interactive analysis view.</li>"
            "<li><b>Save Current Plot</b>.</li>"
            "<li><b>Save All Plots…</b>: choose one or more plot types and "
            "export those types for every available parameter. Interpolated "
            "Map is selected by default and the dialog reports how many files "
            "will be created.</li>"
            "</ul>"
            "<p>Axis range changes are visualization-only; measurements outside "
            "the visible range may still contribute to interpolation. Plot "
            "title, colorbar title, and spatial axes can also be edited by "
            "clicking them directly on the plot.</p>"

            "<h2>15. Parameter Statistics</h2>"
            "<p>The statistics table summarizes all numeric parameters. Ignored "
            "points are always excluded.</p>"
            "<p><b>Statistics Options…</b> chooses between:</p>"
            "<ul>"
            "<li>All included measurements.</li>"
            "<li>Included measurements inside the current displayed plot range.</li>"
            "</ul>"
            "<p>Points outside a selected statistics range are not considered "
            "'ignored'; they are simply outside the statistics scope. "
            "<b>Export Statistics…</b> saves a CSV containing a header that "
            "records the scope, valid-measurement count, explicitly ignored "
            "count, and number of measurements used.</p>"

            "<h2>16. Thickness Line Profile</h2>"
            "<p>When a Thickness parameter is displayed as an "
            "<b>Interpolated Map</b>, the <b>Line Profile</b> button appears. "
            "Select it, then click point A and point B on the map. A separate "
            "window shows interpolated Thickness versus distance along A→B.</p>"
            "<p>This is intended as a qualitative trend tool (for example, to "
            "see whether thickness increases along a direction). Values between "
            "measurement locations are interpolated and should not be treated "
            "as additional direct ellipsometry measurements. Closing the profile "
            "window removes the A–B overlay from the main map.</p>"

            "<h2>17. Recommended Data Philosophy</h2>"
            "<p>AutoMapper automatically preserves raw measurement files and the "
            "parsed mapping_results.csv. Plots and statistics are processed "
            "outputs and are saved only when the user explicitly exports them. "
            "The experiment's <b>results</b> folder is provided as a convenient "
            "default destination for those exports.</p>"

            "<h2>18. Troubleshooting</h2>"
            "<p><b>No recipes appear:</b> verify that the selected measurement "
            "source is connected. For real CompleteEASE, verify the remote "
            "interface and that the recipes are in the CompleteEASE-recognized "
            "recipe location. See the CompleteEASE manual.</p>"
            "<p><b>Point becomes red:</b> AutoMapper did not find a new readable "
            "TXT result for that requested coordinate. The map continues and "
            "the point may be retaken later.</p>"
            "<p><b>Real recipe runs but AutoMapper cannot find data:</b> verify "
            "that the recipe output directory and config.json staging_folder "
            "refer to the same folder.</p>"
            "<p><b>Automatic stage will not move:</b> verify the correct COM port, "
            "stage connection, power, and mapping center. Stage/instrument "
            "hardware troubleshooting is outside the AutoMapper Help window.</p>"
        )
        text.setWordWrap(True)
        text.setTextFormat(text.textFormat())
        layout.addWidget(text)
        layout.addStretch()

        scroll.setWidget(content)
        root.addWidget(scroll)
