"""
ABSTRACT
--------
User manual shown from the AutoMapper Help button.

The Help window is intentionally written as an operating manual for the GUI.
It explains setup, measurement, file handling, Results analysis, exporting, and
common failure behavior without duplicating the CompleteEASE instrument manual.
"""

from PyQt6.QtWidgets import QDialog, QLabel, QScrollArea, QVBoxLayout, QWidget


class HelpDialog(QDialog):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Ellipsometer AutoMapper — User Guide")
        self.resize(780, 760)

        root = QVBoxLayout(self)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)

        content = QWidget()
        layout = QVBoxLayout(content)

        text = QLabel(
            "<h1>Ellipsometer AutoMapper</h1>"
            "<p>AutoMapper performs predefined XY mapping measurements and "
            "user-added single-point measurements, and provides a separate "
            "workspace for mapping analysis. The program "
            "is organized into two main tabs: <b>Measurement</b> and "
            "<b>Results</b>.</p>"

            "<h2>1. Computer Configuration</h2>"
            "<p>Computer-specific paths are stored in <b>config.json</b>. "
            "Two locations are required:</p>"
            "<ul>"
            "<li><b>staging_folder</b>: temporary folder where the selected "
            "CompleteEASE recipe saves its .SE and .txt files.</li>"
            "<li><b>default_experiment_parent</b>: default parent directory "
            "where AutoMapper creates permanent experiment folders.</li>"
            "</ul>"
            "<p>Paths may be absolute or relative. Relative paths are resolved "
            "from the AutoMapper program folder.</p>"

            "<h2>2. CompleteEASE Recipes</h2>"
            "<p>Recipes used with the real instrument must be available in the "
            "standard/common recipe location recognized by CompleteEASE so "
            "that they are returned by <b>ListRecipes()</b>. Configure the "
            "recipe itself to save its acquired data into the same folder "
            "listed as <b>staging_folder</b> in config.json.</p>"
            "<p><b>Important: enable Export Measurement Results in the "
            "CompleteEASE recipe.</b> This export is not enabled by default in "
            "CompleteEASE. The exported result TXT file is AutoMapper's source "
            "of truth for deciding whether a point was successfully acquired "
            "and for loading fitted parameters into Results.</p>"
            "<p>Because AutoMapper recipes are listed from the common/default "
            "CompleteEASE recipe folder, descriptive recipe names are strongly "
            "recommended. A useful naming format is:</p>"
            "<p><b>Purpose - Angle(s) - Acquisition time - Alignment - Model - "
            "Model restrictions</b></p>"
            "<p>Example: <b>Transparent film on silicon - 55 deg - 1 s - Full "
            "alignment - Woollam transparent film on silicon - Fit "
            "1200-1700 nm</b>.</p>"
            "<p>AutoMapper supplies the point filename to the recipe; the recipe "
            "controls the actual measurement, model, alignment steps, and save "
            "location. Refer to the CompleteEASE manual for recipe creation, "
            "alignment, optical models, fitting, and other instrument-specific "
            "settings.</p>"

            "<h2>3. Measurement Source</h2>"
            "<p>At the top of Measurement Setup choose the measurement source:</p>"
            "<ul>"
            "<li><b>SIMULATOR</b>: software-only development mode. It simulates "
            "CompleteEASE, the recipe, and the ellipsometer and writes test "
            "files into the configured staging folder.</li>"
            "<li><b>CompleteEASE</b>: connects to the real CompleteEASE remote "
            "interface on the local computer. CompleteEASE must already be open "
            "and running before AutoMapper connects.</li>"
            "</ul>"
            "<p>Select <b>Connect</b>. After a successful connection, the Recipe "
            "drop-down is populated by that source. The simulator and real "
            "CompleteEASE use the same AutoMapper workflow. Long recipe names "
            "are shown in a wider drop-down; hover over the Recipe control to "
            "see the complete selected name.</p>"

            "<h2>4. Measurement Setup</h2>"
            "<p><b>Recipe:</b> choose the recipe to run at every measured point.</p>"
            "<p><b>Map name:</b> optional descriptive name. AutoMapper always "
            "adds a timestamp, so the experiment folder remains unique.</p>"
            "<p><b>Save location:</b> parent directory for the experiment. Each "
            "new run creates a new timestamped subfolder; measurements from "
            "different experiments are never intentionally combined.</p>"
            "<p><b>Grid:</b> choose the square map size. <b>Spacing</b> is the "
            "center-to-center distance between mapping positions in millimeters. "
            "Mapping span and total point count are shown automatically.</p>"

            "<h3>Experiment Folder</h3>"
            "<p>A run is stored approximately as:</p>"
            "<p><b>YYYYMMDD_HHMMSS_OptionalName/</b><br>"
            "&nbsp;&nbsp;raw_data/ &nbsp;(.SE and .txt point files)<br>"
            "&nbsp;&nbsp;results/ &nbsp;(recommended location for user exports)<br>"
            "&nbsp;&nbsp;mapping_results.csv</p>"
            "<p>Raw point filenames use their map coordinates, for example "
            "<b>X-4_Y2.txt</b> and <b>X-4_Y2.SE</b>.</p>"

            "<h2>5. Automatic XY Stage</h2>"
            "<p>Select <b>Low-Profile Automatic XY Stage</b>. The stage section "
            "appears below Measurement Setup.</p>"
            "<ol>"
            "<li>Select <b>SIMULATOR</b> for software testing or select the real "
            "COM port and press <b>Connect</b>.</li>"
            "<li>For the real stage, verify that the external mapping-stage "
            "power is ON. Serial communication can connect successfully even "
            "when motor power is not available.</li>"
            "<li>Use the arrow controls and jog step to place the ellipsometer "
            "beam over the desired center of the mapping area. The default jog "
            "step is 2 mm and can be changed as needed. The explicit ▲/▼ buttons "
            "beside the jog value are used instead of the Windows native spin-box "
            "arrows for reliable increment/decrement control.</li>"
            "<li>Select <b>Set Mapping Center</b>. This defines the current stage "
            "position as map coordinate (0, 0).</li>"
            "</ol>"
            "<p>The automatic snake sequence starts at the <b>top-left</b> "
            "measurement position, moves right across the first row, then down "
            "one row and left, continuing in an alternating snake pattern.</p>"
            "<p>After a normally completed automatic <b>grid sequence</b>, the "
            "stage returns to the mapping center (0, 0). Single-point "
            "measurements and remeasurements do <b>not</b> automatically return "
            "to center. <b>Abort does not command an automatic return-to-center "
            "move.</b></p>"
            "<p>Once an experiment has begun, the acquisition setup is locked. "
            "Recipe, map name, save location, grid, spacing, stage type, quality "
            "settings, manual absolute-center values, and <b>Set Mapping Center</b> "
            "cannot be changed until <b>Clear Current Data</b> is used. This keeps "
            "all points and later remeasurements in one experiment on the same "
            "measurement definition and coordinate origin.</p>"

            "<h2>6. Manual Stage</h2>"
            "<p>Select <b>Manual Stage</b> when the user will position the sample "
            "by hand. Before every point, AutoMapper displays the requested map "
            "coordinate.</p>"
            "<p>The prompt is designed for keyboard operation:</p>"
            "<ul>"
            "<li><b>Left / Right arrows</b>: change the highlighted action.</li>"
            "<li><b>Enter</b>: activate the highlighted action.</li>"
            "<li><b>Measure</b>: run the selected CompleteEASE recipe.</li>"
            "<li><b>Skip Point</b>: do not request a measurement; the point is "
            "marked as missing and mapping continues.</li>"
            "<li><b>Abort</b>: stop requesting additional mapping points.</li>"
            "</ul>"
            "<p><b>Track absolute coordinates</b> is optional. Enter the X/Y "
            "reading of the manual stage at the map center. The prompt then "
            "shows both the relative map coordinate and the absolute stage "
            "position. Absolute coordinates are only an operator aid; filenames "
            "and Results always use the relative map coordinates.</p>"

            "<h2>7. Before Starting a Real Mapping Run</h2>"
            "<ol>"
            "<li>Place the sample at the intended center and verify that the "
            "ellipsometer can acquire useful data there.</li>"
            "<li>Run the intended recipe manually in CompleteEASE at least once.</li>"
            "<li>Confirm that the optical model and fitted parameters are "
            "appropriate for the sample.</li>"
            "<li>Confirm that the recipe writes its .SE/.txt output to the "
            "configured staging folder.</li>"
            "<li>Confirm that <b>Export Measurement Results</b> is enabled in "
            "the recipe so the result TXT file is produced.</li>"
            "<li>Confirm that CompleteEASE is already open and running before "
            "connecting the real measurement source in AutoMapper.</li>"
            "<li>If using the automatic stage, confirm that stage power is ON "
            "before testing motion or starting the map.</li>"
            "<li>If the recipe performs alignment at every point, it can handle "
            "local alignment during the map. If alignment is intentionally "
            "omitted, prepare the recipe/sample according to the CompleteEASE "
            "procedure before starting AutoMapper.</li>"
            "</ol>"

            "<h2>8. Measurement Quality</h2>"
            "<p><b>Measurement Quality…</b> can flag measurements whose MSE "
            "exceeds a user-defined threshold. A high-MSE point is shown in "
            "orange in the Measurement progress map. This is a warning only; "
            "the measurement remains valid and is not automatically excluded "
            "from Results.</p>"

            "<h2>9. Starting, Single Points, Aborting, and Remeasurement</h2>"
            "<p>Select <b>Start Measurement</b> after the measurement source is "
            "connected and the setup is valid. This starts the complete grid "
            "sequence in a new timestamped experiment folder.</p>"
            "<p>The small menu button beside Start Measurement provides "
            "<b>Add Single Point…</b>. Single points are added to the current "
            "experiment; if no experiment exists yet, the first point creates "
            "one. Additional single points continue to use that same experiment "
            "until <b>Clear Current Data</b> is used. A new grid sequence cannot "
            "be started while a current experiment is active.</p>"
            "<p>For the automatic stage, the Single Point window provides jog "
            "arrows, a jog-step control, the current relative X/Y coordinate, "
            "and <b>Measure Point</b>. For a manual stage, enter the desired "
            "relative coordinate; when absolute tracking is enabled on the main "
            "Measurement page, linked absolute coordinates are also shown. Manual "
            "single-point coordinate fields use explicit ▲/▼ buttons rather than "
            "the native Windows/Qt spin-box arrows.</p>"
            "<p>Map-coordinate filenames currently use whole-millimeter X/Y "
            "coordinates. The operator may use fine jog increments for alignment, "
            "but measurement is enabled only at whole-millimeter map coordinates.</p>"
            "<p><b>Abort</b> stops the AutoMapper sequence. It does not attempt "
            "to cancel a CompleteEASE recipe already in progress; the current "
            "request is allowed to finish and no next point is requested.</p>"
            "<p>After each CompleteEASE request, AutoMapper first preserves any "
            "new .SE and .txt files in the experiment raw_data folder, then "
            "attempts to interpret the TXT for Results. Raw files are therefore "
            "kept even when AutoMapper cannot parse the result.</p>"
            "<p>A new .SE file means measurement data were acquired. If the .SE "
            "exists but no usable TXT result is available, the Measurement point "
            "is shown as a red X and has no Results-table row. If no new .SE is "
            "produced, the point remains gray. Skipped points also remain gray.</p>"
            "<p>When a coordinate is measured again, newly produced files are "
            "preserved without destroying a previously valid result. Repeated "
            "attempt files may be stored under raw_data/repeated_attempts.</p>"
            "<p>A CompleteEASE communication failure is different: AutoMapper "
            "stops the mapping sequence and displays an error message. Verify "
            "that CompleteEASE is still open and running before reconnecting.</p>"
            "<p>Select a pending, measured, or failed point in the progress map "
            "(or a measured row in the table) and use <b>Measure Selected Point</b>. "
            "This can acquire an unmeasured planned point or remeasure an existing "
            "point. If a new measurement of a previously valid point fails, the "
            "previous valid permanent result is kept. No automatic return-to-center "
            "move is performed after this operation.</p>"
            "<p><b>Clear Current Data</b> clears the current Measurement and Results "
            "dataset and releases the mapping-origin lock. It does <b>not</b> "
            "delete the already saved experiment folder from disk. The next "
            "measurement creates a new timestamped experiment folder.</p>"

            "<h2>10. Measurement Progress</h2>"
            "<p>For a grid sequence, the progress map shows the planned grid. "
            "For user-added single points, it acts as a live XY scatter plot and "
            "grows as points are measured. Single points may also be added to an "
            "existing grid experiment.</p>"
            "<p>Point colors/status are:</p>"
            "<ul>"
            "<li>Gray: not yet measured, skipped, or no new .SE measurement file</li>"
            "<li>Yellow: current acquisition</li>"
            "<li>Green: acquired measurement with usable Results data</li>"
            "<li>Orange: usable Results data above the selected MSE warning threshold</li>"
            "<li>Red X: measurement data exist, but no usable Results TXT is available</li>"
            "</ul>"
            "<p>Map-point and table-row selection are linked. Clicking the "
            "currently selected item again clears the selection.</p>"
            "<p>A small red laser-like dot indicates the stage position on the "
            "progress map. For the automatic stage it follows jog and automatic "
            "moves. For a manual stage, AutoMapper places it at the coordinate "
            "the operator confirms for measurement. The red dot is intentionally "
            "smaller than a measurement point so the point status color remains "
            "visible underneath it.</p>"
            "<p>Selecting <b>Set Mapping Center</b> for the automatic stage does "
            "not physically move the stage; it redefines the current physical "
            "position as (0, 0), so the marker moves to the center coordinate.</p>"

            "<h2>11. Results Data Sources</h2>"
            "<p>Results updates live from the current measurement. It can also "
            "be used independently:</p>"
            "<ul>"
            "<li><b>Import TXT Folder</b>: parse coordinate-named CompleteEASE "
            "TXT result files.</li>"
            "<li><b>Import Table</b>: load an existing CSV table containing X "
            "and Y coordinates plus numeric parameters.</li>"
            "</ul>"
            "<p>The parser also accepts the older coordinate filename form "
            "<b>(-1,0).txt</b>. Imported datasets may contain irregular XY "
            "positions; plot types requiring a regular grid may then be "
            "unavailable.</p>"

            "<h2>12. Results Selection and Ignoring Points</h2>"
            "<p>Click an actual measured point or its table row to select it. "
            "Use <b>Ignore Point</b> to remove that measurement from interpolation "
            "and statistics. An ignored valid point appears as a red X during "
            "analysis and may be re-enabled. Missing/failed points do not exist "
            "as Results rows and therefore cannot be enabled.</p>"
            "<p>Ignored, missing, and temporary selected-point markers are not "
            "shown as data in exported scientific plots.</p>"

            "<h2>13. Plot Types</h2>"
            "<ul>"
            "<li><b>Interpolated Map</b>: continuous interpolated color map.</li>"
            "<li><b>Contour Map</b>: interpolated map with contour lines.</li>"
            "<li><b>Measured Points + Values</b>: actual measured coordinates "
            "with numerical labels.</li>"
            "<li><b>Pixel / Cell Map</b>: regular-grid cells without continuous "
            "interpolation; available only when the coordinates form a regular grid.</li>"
            "<li><b>3D Surface</b>: three-dimensional visualization of the "
            "interpolated surface.</li>"
            "<li><b>Histogram</b>: distribution of the selected parameter over "
            "included measured points.</li>"
            "</ul>"

            "<h2>14. Plot Options and Export</h2>"
            "<p><b>Plot Options…</b> is the primary location for plot formatting "
            "and export. It includes:</p>"
            "<ul>"
            "<li>Plot title and colorbar title.</li>"
            "<li>X/Y axis ranges: Auto or user-defined.</li>"
            "<li>X/Y tick spacing: Auto or user-defined.</li>"
            "<li><b>Reset Plot Settings</b>.</li>"
            "<li><b>Include measured-point markers</b> for exported plots. "
            "Markers remain visible in the interactive analysis view.</li>"
            "<li><b>Save Current Plot</b>.</li>"
            "<li><b>Save All Plots…</b>: choose one or more plot types and "
            "export those types for every available parameter. Interpolated "
            "Map is selected by default and the dialog reports how many files "
            "will be created.</li>"
            "</ul>"
            "<p>Axis range changes are visualization-only; measurements outside "
            "the visible range may still contribute to interpolation. Plot "
            "title, colorbar title, and spatial axes can also be edited by "
            "clicking them directly on the plot.</p>"

            "<h2>15. Parameter Statistics</h2>"
            "<p>The statistics table summarizes all numeric parameters. Ignored "
            "points are always excluded.</p>"
            "<p><b>Statistics Options…</b> chooses between:</p>"
            "<ul>"
            "<li>All included measurements.</li>"
            "<li>Included measurements inside the current displayed plot range.</li>"
            "</ul>"
            "<p>Points outside a selected statistics range are not considered "
            "'ignored'; they are simply outside the statistics scope. "
            "<b>Export Statistics…</b> saves a CSV containing a header that "
            "records the scope, valid-measurement count, explicitly ignored "
            "count, and number of measurements used.</p>"

            "<h2>16. Point Statistics</h2>"
            "<p>On supported 2D spatial plots, select <b>Point Statistics</b> and "
            "click a measured point. Hold <b>Ctrl</b> while clicking to add or "
            "remove multiple points. Statistics update for the selected points.</p>"
            "<p>Ignored points are not selectable. Closing the Point Statistics "
            "window clears the Point Statistics selection and does not change "
            "any point's Ignore/Enable state.</p>"

            "<h2>17. Thickness Line Profile</h2>"
            "<p>When a Thickness parameter is displayed as an "
            "<b>Interpolated Map</b>, the <b>Line Profile</b> button appears. "
            "Select it, then click point A and point B on the map. A separate "
            "window shows interpolated Thickness versus distance along A→B.</p>"
            "<p>This is intended as a qualitative trend tool (for example, to "
            "see whether thickness increases along a direction). Values between "
            "measurement locations are interpolated and should not be treated "
            "as additional direct ellipsometry measurements. Closing the profile "
            "window removes the A–B overlay from the main map.</p>"

            "<h2>18. Recommended Data Philosophy</h2>"
            "<p>AutoMapper automatically preserves raw measurement files and the "
            "parsed mapping_results.csv. Plots and statistics are processed "
            "outputs and are saved only when the user explicitly exports them. "
            "The experiment's <b>results</b> folder is provided as a convenient "
            "default destination for those exports.</p>"

            "<h2>19. Troubleshooting</h2>"
            "<p><b>Cannot connect to CompleteEASE:</b> make sure CompleteEASE "
            "is already open and running on the same computer, then reconnect "
            "the CompleteEASE measurement source.</p>"
            "<p><b>No recipes appear:</b> verify that the selected measurement "
            "source is connected. For real CompleteEASE, verify the remote "
            "interface and that the recipes are in the CompleteEASE-recognized "
            "recipe location. See the CompleteEASE manual.</p>"
            "<p><b>Point remains gray after an attempt:</b> no new .SE measurement "
            "file was produced, or the point was intentionally skipped.</p>"
            "<p><b>Point becomes red:</b> a new measurement .SE file exists, but "
            "AutoMapper did not obtain usable Results data from the TXT export. "
            "The raw files remain saved and the point may be measured again later "
            "with Measure Selected Point or reanalyzed in CompleteEASE.</p>"
            "<p><b>Real recipe runs but AutoMapper cannot find data:</b> verify "
            "that the recipe output directory and config.json staging_folder "
            "refer to the same folder, and verify that <b>Export Measurement "
            "Results</b> is enabled in the CompleteEASE recipe.</p>"
            "<p><b>Automatic stage will not move:</b> verify the correct COM port, "
            "stage connection, power, and mapping center. Stage/instrument "
            "hardware troubleshooting is outside the AutoMapper Help window.</p>"
        )
        text.setWordWrap(True)
        text.setTextFormat(text.textFormat())
        layout.addWidget(text)
        layout.addStretch()

        scroll.setWidget(content)
        root.addWidget(scroll)
